# El nombre que recibe el pipeline
name: Integracion Continua

# Los pasos para ejecutar el pipeline
jobs:
  create-database:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/mysql@v1
        with:
          host: localhost
          user: root
          password: root
          database: atko
        run: |
          CREATE DATABASE atko;

  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v2

      - name: Configurar el JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: "zulu"

      - name: Ejecutar las pruebas
        run: ./gradlew test --no-daemon

# Ejecutar el pipeline en cada push sobre la rama "master"
on:
  push:
    branches:
      - actions